= ユーザーインターフェース設計書

== 機能一覧

- HTMLページの公開
- ボイスの登録

== システム構成

課金不要のウェブページとしてGitHub Pagesを使用する。 +
GitHub Pagesは機能制限があるが、初期の規模では問題ないと判断する。 +
GitHub Pagesの機能制限については以下

TODO 機能制限を記載

音声ファイル及びhtmlファイルをリポジトリで管理する。 +
htmlファイルは GitHub Actions により音声ファイル追加時に生成する。 +
jsによりクライアント側で動的に生成することもできるが、GithubPagesのアクセス数制限に
対応してアクセス数を緩和するため、htmlファイルをあらかじめ生成しておく。

ボイスの登録作業は、Githubのプルリクエスト機能を利用して、直接リポジトリ内の音声ファイルを編集してもらうことで実現する。 +
htmlページは自動更新されるため音声登録者は編集する必要はない。

htmlページの掲載情報、CSS等は随時有志により更新可能にする。

== フォルダ構成

音声ファイルとそれに対応するjson形式のメタデータファイルをvoicesフォルダに格納していく。 +
既存サイトではファイル一覧を一つのjsonファイルにしているが、以下の理由により1音声ファイル１メタデータに紐づくようにする

****
- ボイスの数が多くなった際に、メタデータファイルのサイズが大きくなってしまい、編集がしづらくなる
- ボイス追加を複数人が行う際に一つのファイルを編集しなければならない場合、マージ時にコンフリクトが発生する可能性がある
- 将来的にクラウドサービスに移管した場合に、オブジェクトストレージのオブジェクト（とそのオブジェクトのメタデータ）の形式に変換して移行しやすい。
オブジェクトストレージ上のファイルは管理者以外編集できないため、アップロードしてもらう際に音声ファイルとそのメタデータを入力する形をとる必要がある。
****

=== ファイル名

他の既存サイトに合わせて、ファイル名は音声ファイルの内容を全角で記載したモノとする。 +
内容がかぶった場合は、後ろに半角数字で 2~ の数字を付けていく。 +

|===
|===

[NOTE]
====
完全に番号だけにする案や、MD5のハッシュをファイル名にする案もあるが、
連番だと複数人での作業時にぶつかる可能性があること、またMD5も含めてファイル名名から内容が分かりづらいことから不採用とした。

もし何ら中の理由によりMD5案を採用する場合は、htmlを自動生成するときに、json形式でファイル一覧リストを出力するようにする
====

== ファイルフォーマット詳細

既存サービスを参考にする（仮）

```
{
        "title": "ば～っかにしてんのか～？",
        "path": "1.mp3",
        "actor": [ "兎鞠まり" ],
        "tags": [ "威嚇" ],
        "source": "https://youtu.be/eZnyVrfNN-w?t=1h45m24s",
        "relatives": {
                "twitter": [
                        "https://twitter.com/tomari_mari/status/1035278733152739328"
                ]
        }
}
```
https://tomaributton.azurewebsites.net/howtomake/

== 表示フォーマット

音声ファイルをグルーピングするのに既存サイトでは以下の二つの方法がとられている

- ソースの配信でくくる
- 独自につけたタグ（挨拶、笑い、etc）でくくる

仮実装ではタグでのグルーピングを行う

== 対応音源ファイル

サーバへの帯域負荷を考え圧縮音源のみ対応とする。 +
特別高音質ファイルがアップロードされることに対してのチェックロジックは実装しない。 +
あくまでサポート対象外になるという意味である。

対応ファイル形式は以下（仮）

- mp3
- m4a
